In [1]:
import pandas as pd

In [6]:
pd.read_csv("7-Morroco-Senegal.csv")

,id,event_id,minute,second,team_id,x,y,expanded_minute,satisfiedEventsTypes,is_touch,...,AerialFoul,LeadingToGoal,HighCentre,SmallBoxCentre,SixYardBlock,SmallBoxLeft,HighClaim,OutOfBoxRight,KeeperSaveObox,ParriedDanger
0,2.890851e+09,3,0,0.0,495,50.2,50.2,0,"[91, 117, 30, 35, 38, 216, 218]",True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2.890851e+09,4,0,5.0,495,36.9,40.6,0,"[91, 120, 128, 36, 38, 217, 218]",True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2.890851e+09,4,0,15.0,957,36.5,100.0,0,"[91, 212, 35, 38, 215]",True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2.890851e+09,5,0,18.0,957,9.9,88.7,0,"[91, 117, 30, 35, 38, 215, 218]",True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2.890851e+09,6,0,21.0,957,6.8,56.0,0,"[91, 117, 124, 127, 36, 38, 216, 218]",True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1756,2.890911e+09,1003,123,5.0,957,75.4,0.0,152,"[91, 212, 36, 37, 217]",True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1757,2.890911e+09,1038,123,9.0,495,4.2,94.7,152,"[91, 101, 56]",True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1758,2.890911e+09,1039,123,10.0,495,8.8,94.2,152,"[91, 63]",True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1759,2.890911e+09,1004,123,10.0,957,91.1,5.8,152,[64],False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1760,2.890911e+09,1040,123,25.0,495,17.4,88.0,152,"[91, 120, 128, 133, 36, 38, 216, 218]",True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
pd.read_csv("6-Morroco-Nigeria.csv")

,id,event_id,minute,second,team_id,x,y,expanded_minute,satisfiedEventsTypes,is_touch,...,SmallBoxRight,LowCentre,PlayerPosition,JerseyNumber,FormationSlot,Throughball,KeeperMissed,Penalty,PenaltyShootoutConcededGK,KeeperSaved
0,2.889504e+09,3,0,0,495,50.3,50.1,0,"[91, 117, 30, 35, 38, 215, 218]",True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2.889504e+09,4,0,4,495,31.1,37.5,0,"[91, 120, 128, 36, 38, 217, 218]",True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2.889504e+09,4,0,9,977,28.0,86.8,0,[91],True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2.889505e+09,7,0,18,495,93.0,0.0,0,"[91, 212, 35, 37, 217]",True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2.889505e+09,8,0,22,495,77.8,7.3,0,"[91, 119, 117, 30, 35, 37, 216, 218]",True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1859,2.889579e+09,1089,127,11,977,88.5,50.0,134,"[91, 209]",True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN
1860,2.889579e+09,1101,127,11,495,0.0,0.0,134,[],False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.0
1861,2.889579e+09,1102,127,11,495,99.8,47.9,134,"[91, 109, 210, 77, 79, 81]",True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN
1862,2.889580e+09,1090,127,58,977,0.0,0.0,134,"[116, 211]",False,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,NaN
1863,2.889579e+09,1103,127,58,495,88.5,50.0,134,"[91, 207]",True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN