In [27]:
from curl_cffi import requests
from bs4 import BeautifulSoup

In [28]:
url = "https://www.whoscored.com/matches/1914256/live/spain-laliga-2025-2026-real-madrid-athletic-club"

In [29]:
headers = {
            "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
            "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8",
            "accept-language": "en-US,en;q=0.9",
            "referer": "https://www.google.com/"
}
response = requests.get(url,headers = headers, impersonate = "chrome120", timeout = 30)
soup = BeautifulSoup(response.text, 'html.parser')
soup

<!DOCTYPE html>

<html lang="en">
<head><script defer="" src="https://cx-resources.oddschecker.com/fingerprint/verify-client.js?v1.0.1"></script>
<link href="https://d2zywfiolv4f83.cloudfront.net/" rel="dns-prefetch"/>
<link crossorigin="" href="https://d2zywfiolv4f83.cloudfront.net/" rel="preconnect"/>
<meta content="width=device-width, initial-scale=1" name="viewport"/>
<meta content="app-id=940048063" name="apple-itunes-app"/>
<!-- #9 -->
<meta content="text/html; charset=utf-8" http-equiv="content-type"/>
<meta content="IE=Edge" http-equiv="X-UA-Compatible"/><script type="text/javascript">window.NREUM||(NREUM={});NREUM.info = {"beacon":"bam.nr-data.net","errorBeacon":"bam.nr-data.net","licenseKey":"47235c2cb5","applicationID":"1020889913","transactionName":"MVBVZhMHDEcCV0BdCwgadmExSRRdBkNHGwkHQVRaBBVNWQJAV1wHA1tDQARIA0cTTA==","queueTime":0,"applicationTime":485,"agent":"","atts":""}</script><script type="text/javascript">(window.NREUM||(NREUM={})).init={ajax:{deny_list:["bam.nr-data.net"]},feature_flags:["soft_nav"]};(window.NREUM||(NREUM={})).loader_config={licenseKey:"47235c2cb5",applicationID:"1020889913",browserID:"1120121425"};window.NREUM||(NREUM={}),__nr_require=function(t,e,n){function r(n){if(!e[n]){var i=e[n]={exports:{}};t[n][0].call(i.exports,function(e){var i=t[n][1][e];return r(i||e)},i,i.exports)}return e[n].exports}if("function"==typeof __nr_require)return __nr_require;for(var i=0;i<n.length;i++)r(n[i]);return r}({1:[function(t,e,n){function r(){}function i(t,e,n,r){return function(){return s.recordSupportability("API/"+e+"/called"),o(t+e,[u.now()].concat(c(arguments)),n?null:this,r),n?void 0:this}}var o=t("handle"),a=t(9),c=t(10),f=t("ee").get("tracer"),u=t("loader"),s=t(4),d=NREUM;"undefined"==typeof window.newrelic&&(newrelic=d);var p=["setPageViewName","setCustomAttribute","setErrorHandler","finished","addToTrace","inlineHit","addRelease"],l="api-",v=l+"ixn-";a(p,function(t,e){d[e]=i(l,e,!0,"api")}),d.addPageAction=i(l,"addPageAction",!0),d.setCurrentRouteName=i(l,"routeName",!0),e.exports=newrelic,d.interaction=function(){return(new r).get()};var m=r.prototype={createTracer:function(t,e){var n={},r=this,i="function"==typeof e;return o(v+"tracer",[u.now(),t,n],r),function(){if(f.emit((i?"":"no-")+"fn-start",[u.now(),r,i],n),i)try{return e.apply(this,arguments)}catch(t){throw f.emit("fn-err",[arguments,this,t],n),t}finally{f.emit("fn-end",[u.now()],n)}}}};a("actionText,setName,setAttribute,save,ignore,onEnd,getContext,end,get".split(","),function(t,e){m[e]=i(v,e)}),newrelic.noticeError=function(t,e){"string"==typeof t&&(t=new Error(t)),s.recordSupportability("API/noticeError/called"),o("err",[t,u.now(),!1,e])}},{}],2:[function(t,e,n){function r(t){if(NREUM.init){for(var e=NREUM.init,n=t.split("."),r=0;r<n.length-1;r++)if(e=e[n[r]],"object"!=typeof e)return;return e=e[n[n.length-1]]}}e.exports={getConfiguration:r}},{}],3:[function(t,e,n){var r=!1;try{var i=Object.defineProperty({},"passive",{get:function(){r=!0}});window.addEventListener("testPassive",null,i),window.removeEventListener("testPassive",null,i)}catch(o){}e.exports=function(t){return r?{passive:!0,capture:!!t}:!!t}},{}],4:[function(t,e,n){function r(t,e){var n=[a,t,{name:t},e];return o("storeMetric",n,null,"api"),n}function i(t,e){var n=[c,t,{name:t},e];return o("storeEventMetrics",n,null,"api"),n}var o=t("handle"),a="sm",c="cm";e.exports={constants:{SUPPORTABILITY_METRIC:a,CUSTOM_METRIC:c},recordSupportability:r,recordCustom:i}},{}],5:[function(t,e,n){function r(){return c.exists&&performance.now?Math.round(performance.now()):(o=Math.max((new Date).getTime(),o))-a}function i(){return o}var o=(new Date).getTime(),a=o,c=t(11);e.exports=r,e.exports.offset=a,e.exports.getLastTimestamp=i},{}],6:[function(t,e,n){function r(t,e){var n=t.getEntries();n.forEach(function(t){"first-paint"===t.name?l("timing",["fp",Math.floor(t.startTime)]):"first-contentful-paint"===t.name&&l("timing",["fcp",Math.floor(t.startTime)])})}function i(t,e){var n=t.getEntries();if(n.length>0){var r=n[n.length-1];if(u&&u<r.startTime)return;var i=[r],o=a({});o&&i.push(o),l("lcp",i)}}function o(t){t.getEntries().forEach(function(t){t.hadRecentInput||l("cls",[t])})}function a(t){var e=navigator.connection||navigator.mozConnection||navigator.webkitConnection;if(e)return e.type&&(t["net-type"]=e.type),e.effectiveType&&(t["net-etype"]=e.effectiveType),e.rtt&&(t["net-rtt"]=e.rtt),e.downlink&&(t["net-dlink"]=e.downlink),t}function c(t){if(t instanceof y&&!w){var e=Math.round(t.timeStamp),n={type:t.type};a(n),e<=v.now()?n.fid=v.now()-e:e>v.offset&&e<=Date.now()?(e-=v.offset,n.fid=v.now()-e):e=v.now(),w=!0,l("timing",["fi",e,n])}}function f(t){"hidden"===t&&(u=v.now(),l("pageHide",[u]))}if(!("init"in NREUM&&"page_view_timing"in NREUM.init&&"enabled"in NREUM.init.page_view_timing&&NREUM.init.page_view_timing.enabled===!1)){var u,s,d,p,l=t("handle"),v=t("loader"),m=t(8),g=t(3),y=NREUM.o.EV;if("PerformanceObserver"in window&&"function"==typeof window.PerformanceObserver){s=new PerformanceObserver(r);try{s.observe({entryTypes:["paint"]})}catch(h){}d=new PerformanceObserver(i);try{d.observe({entryTypes:["largest-contentful-paint"]})}catch(h){}p=new PerformanceObserver(o);try{p.observe({type:"layout-shift",buffered:!0})}catch(h){}}if("addEventListener"in document){var w=!1,b=["click","keydown","mousedown","pointerdown","touchstart"];b.forEach(function(t){document.addEventListener(t,c,g(!1))})}m(f)}},{}],7:[function(t,e,n){function r(t,e){if(!i)return!1;if(t!==i)return!1;if(!e)return!0;if(!o)return!1;for(var n=o.split("."),r=e.split("."),a=0;a<r.length;a++)if(r[a]!==n[a])return!1;return!0}var i=null,o=null,a=/Version\/(\S+)\s+Safari/;if(navigator.userAgent){var c=navigator.userAgent,f=c.match(a);f&&c.indexOf("Chrome")===-1&&c.indexOf("Chromium")===-1&&(i="Safari",o=f[1])}e.exports={agent:i,version:o,match:r}},{}],8:[function(t,e,n){function r(t){function e(){t(c&&document[c]?document[c]:document[o]?"hidden":"visible")}"addEventListener"in document&&a&&document.addEventListener(a,e,i(!1))}var i=t(3);e.exports=r;var o,a,c;"undefined"!=typeof document.hidden?(o="hidden",a="visibilitychange",c="visibilityState"):"undefined"!=typeof document.msHidden?(o="msHidden",a="msvisibilitychange"):"undefined"!=typeof document.webkitHidden&&(o="webkitHidden",a="webkitvisibilitychange",c="webkitVisibilityState")},{}],9:[function(t,e,n){function r(t,e){var n=[],r="",o=0;for(r in t)i.call(t,r)&&(n[o]=e(r,t[r]),o+=1);return n}var i=Object.prototype.hasOwnProperty;e.exports=r},{}],10:[function(t,e,n){function r(t,e,n){e||(e=0),"undefined"==typeof n&&(n=t?t.length:0);for(var r=-1,i=n-e||0,o=Array(i<0?0:i);++r<i;)o[r]=t[e+r];return o}e.exports=r},{}],11:[function(t,e,n){e.exports={exists:"undefined"!=typeof window.performance&&window.performance.timing&&"undefined"!=typeof window.performance.timing.navigationStart}},{}],ee:[function(t,e,n){function r(){}function i(t){function e(t){return t&&t instanceof r?t:t?u(t,f,a):a()}function n(n,r,i,o,a){if(a!==!1&&(a=!0),!l.aborted||o){t&&a&&t(n,r,i);for(var c=e(i),f=m(n),u=f.length,s=0;s<u;s++)f[s].apply(c,r);var p=d[w[n]];return p&&p.push([b,n,r,c]),c}}function o(t,e){h[t]=m(t).concat(e)}function v(t,e){var n=h[t];if(n)for(var r=0;r<n.length;r++)n[r]===e&&n.splice(r,1)}function m(t){return h[t]||[]}function g(t){return p[t]=p[t]||i(n)}function y(t,e){l.aborted||s(t,function(t,n){e=e||"feature",w[n]=e,e in d||(d[e]=[])})}var h={},w={},b={on:o,addEventListener:o,removeEventListener:v,emit:n,get:g,listeners:m,context:e,buffer:y,abort:c,aborted:!1};return b}function o(t){return u(t,f,a)}function a(){return new r}function c(){(d.api||d.feature)&&(l.aborted=!0,d=l.backlog={})}var f="nr@context",u=t("gos"),s=t(9),d={},p={},l=e.exports=i();e.exports.getOrSetContext=o,l.backlog=d},{}],gos:[function(t,e,n){function r(t,e,n){if(i.call(t,e))return t[e];var r=n();if(Object.defineProperty&&Object.keys)try{return Object.defineProperty(t,e,{value:r,writable:!0,enumerable:!1}),r}catch(o){}return t[e]=r,r}var i=Object.prototype.hasOwnProperty;e.exports=r},{}],handle:[function(t,e,n){function r(t,e,n,r){i.buffer([t],r),i.emit(t,e,n)}var i=t("ee").get("handle");e.exports=r,r.ee=i},{}],id:[function(t,e,n){function r(t){var e=typeof t;return!t||"object"!==e&&"function"!==e?-1:t===window?0:a(t,o,function(){return i++})}var i=1,o="nr@id",a=t("gos");e.exports=r},{}],loader:[function(t,e,n){function r(){if(!M++){var t=T.info=NREUM.info,e=m.getElementsByTagName("script")[0];if(setTimeout(u.abort,3e4),!(t&&t.licenseKey&&t.applicationID&&e))return u.abort();f(x,function(e,n){t[e]||(t[e]=n)});var n=a();c("mark",["onload",n+T.offset],null,"api"),c("timing",["load",n]);var r=m.createElement("script");0===t.agent.indexOf("http://")||0===t.agent.indexOf("https://")?r.src=t.agent:r.src=l+"://"+t.agent,e.parentNode.insertBefore(r,e)}}function i(){"complete"===m.readyState&&o()}function o(){c("mark",["domContent",a()+T.offset],null,"api")}var a=t(5),c=t("handle"),f=t(9),u=t("ee"),s=t(7),d=t(2),p=t(3),l=d.getConfiguration("ssl")===!1?"http":"https",v=window,m=v.document,g="addEventListener",y="attachEvent",h=v.XMLHttpRequest,w=h&&h.prototype,b=!1;NREUM.o={ST:setTimeout,SI:v.setImmediate,CT:clearTimeout,XHR:h,REQ:v.Request,EV:v.Event,PR:v.Promise,MO:v.MutationObserver};var E=""+location,x={beacon:"bam.nr-data.net",errorBeacon:"bam.nr-data.net",agent:"js-agent.newrelic.com/nr-1216.min.js"},O=h&&w&&w[g]&&!/CriOS/.test(navigator.userAgent),T=e.exports={offset:a.getLastTimestamp(),now:a,origin:E,features:{},xhrWrappable:O,userAgent:s,disabled:b};if(!b){t(1),t(6),m[g]?(m[g]("DOMContentLoaded",o,p(!1)),v[g]("load",r,p(!1))):(m[y]("onreadystatechange",i),v[y]("onload",r)),c("mark",["firstbyte",a.getLastTimestamp()],null,"api");var M=0}},{}],"wrap-function":[function(t,e,n){function r(t,e){function n(e,n,r,f,u){function nrWrapper(){var o,a,s,p;try{a=this,o=d(arguments),s="function"==typeof r?r(o,a):r||{}}catch(l){i([l,"",[o,a,f],s],t)}c(n+"start",[o,a,f],s,u);try{return p=e.apply(a,o)}catch(v){throw c(n+"err",[o,a,v],s,u),v}finally{c(n+"end",[o,a,p],s,u)}}return a(e)?e:(n||(n=""),nrWrapper[p]=e,o(e,nrWrapper,t),nrWrapper)}function r(t,e,r,i,o){r||(r="");var c,f,u,s="-"===r.charAt(0);for(u=0;u<e.length;u++)f=e[u],c=t[f],a(c)||(t[f]=n(c,s?f+r:r,i,f,o))}function c(n,r,o,a){if(!v||e){var c=v;v=!0;try{t.emit(n,r,o,e,a)}catch(f){i([f,n,r,o],t)}v=c}}return t||(t=s),n.inPlace=r,n.flag=p,n}function i(t,e){e||(e=s);try{e.emit("internal-error",t)}catch(n){}}function o(t,e,n){if(Object.defineProperty&&Object.keys)try{var r=Object.keys(t);return r.forEach(function(n){Object.defineProperty(e,n,{get:function(){return t[n]},set:function(e){return t[n]=e,e}})}),e}catch(o){i([o],n)}for(var a in t)l.call(t,a)&&(e[a]=t[a]);return e}function a(t){return!(t&&t instanceof Function&&t.apply&&!t[p])}function c(t,e){var n=e(t);return n[p]=t,o(t,n,s),n}function f(t,e,n){var r=t[e];t[e]=c(r,n)}function u(){for(var t=arguments.length,e=new Array(t),n=0;n<t;++n)e[n]=arguments[n];return e}var s=t("ee"),d=t(10),p="nr@original",l=Object.prototype.hasOwnProperty,v=!1;e.exports=r,e.exports.wrapFunction=c,e.exports.wrapInPlace=f,e.exports.argsToArray=u},{}]},{},["loader"]);</script>
<meta content="353f79d2d02f885b1a54bBffe7ab9758f" name="p:domain_verify"/>
<meta content="Real Madrid 4-2 Athletic Club - LaLiga 2025/2026 Live" name="title"/>
<meta content="Real Madrid-Athletic Club live incidents, goals, cards, substitutions, lineups, statistics, formations" name="description"/>
<meta content="Real Madrid-Athletic Club live incidents, goals, cards, substitutions, lineups, statistics, formations" name="keywords"/>
<link href="https://www.whoscored.com/matches/1914256/live/spain-laliga-2025-2026-real-madrid-athletic-club" rel="canonical"/>
<style>
        #live-incidents {
            min-height: 400px ;
        }

    </style>
<title>


    Real Madrid 4-2 Athletic Club - LaLiga 2025/2026 Live


    </title>
<link href="https://d2zywfiolv4f83.cloudfront.net/img/favicon.gif" rel="icon" type="image/gif"/>
<link href="/rss" rel="alternate" title="The latest previews and articles from WhoScored.com" type="application/rss+xml"/>
<style>

In [30]:
import json
element = soup.select_one('script:-soup-contains("matchCentreData")')
element

<script>
        require.config.params["args"] = {
            matchId:1914256,

In [39]:
import pandas as pd
import json5
raw_text = element.text.split("matchCentreData: ")[1].strip()
data, _ = json.JSONDecoder().raw_decode(raw_text) #Got it converted to json format
evs = (data[('events')])
type(evs)

list

In [42]:
data

{'playerIdNameDictionary': {'514810': 'Franco Mastantuono',
  '39722': 'David Alaba',
  '73798': 'Thibaut Courtois',
  '300713': 'Kylian Mbappé',
  '353423': 'Aurélien Tchouaméni',
  '369109': 'Eduardo Camavinga',
  '104010': 'Antonio Rüdiger',
  '317541': 'Brahim Díaz',
  '106883': 'Dani Carvajal',
  '144890': 'Dani Ceballos',
  '534899': 'Raúl Asencio',
  '437583': 'Álvaro Carreras',
  '468852': 'Dean Huijsen',
  '498798': 'Gonzalo García',
  '415181': 'Arda Güler',
  '345031': 'Andrii Lunin',
  '344644': 'Federico Valverde',
  '379868': 'Jude Bellingham',
  '422957': 'Fran García',
  '577403': 'Thiago Pitarch',
  '623489': 'Álvaro González',
  '623490': 'Manuel Serrano',
  '255182': 'Iñaki Williams',
  '541704': 'Maroan Sannadi',
  '106586': 'Íñigo Ruíz de Galarreta',
  '122117': 'Aymeric Laporte',
  '261516': 'Mikel Vesga',
  '279839': 'Yeray Álvarez',
  '291686': 'Íñigo Lekue',
  '332823': 'Unai Simón',
  '345908': 'Andoni Gorosabel',
  '357839': 'Dani Vivian',
  '362602': 'Gorka Guruzeta',
  '400237': 'Robert Navarro',
  '402663': 'Aitor Paredes',
  '414643': 'Beñat Prados',
  '422820': 'Jesús Areso',
  '423109': 'Nico Serrano',
  '449383': 'Álex Padilla',
  '463431': 'Urko Izeta',
  '480619': 'Unai Gómez',
  '511120': 'Mikel Jauregizar',
  '515307': 'Adama Boiro',
  '560362': 'Alejandro Rego',
  '607204': 'Elijah Gift'},
 'periodMinuteLimits': {'1': 45, '2': 90, '3': 105, '4': 120},
 'timeStamp': '2026-05-24 01:32:36',
 'attendance': 70398,
 'venueName': 'Estadio Bernabéu',
 'referee': {'officialId': 206,
  'firstName': 'Juan',
  'lastName': 'Martínez Munuera',
  'hasParticipatedMatches': False,
  'name': 'Juan Martínez Munuera'},
 'weatherCode': '',
 'elapsed': 'FT',
 'startTime': '2026-05-23T20:00:00',
 'startDate': '2026-05-23T00:00:00',
 'score': '4 : 2',
 'htScore': '2 : 1',
 'ftScore': '4 : 2',
 'etScore': '',
 'pkScore': '',
 'statusCode': 6,
 'periodCode': 7,
 'home': {'teamId': 52,
  'formations': [{'formationId': 2,
    'formationName': '442',
    'captainPlayerId': 106883,
    'period': 16,
    'startMinuteExpanded': 0,
    'endMinuteExpanded': 73,
    'jerseyNumbers': [1,
     2,
     18,
     5,
     17,
     4,
     30,
     8,
     10,
     16,
     45,
     13,
     6,
     14,
     15,
     19,
     20,
     21,
     22,
     24,
     50,
     51],
    'formationSlots': [1,
     2,
     3,
     4,
     5,
     6,
     7,
     8,
     9,
     10,
     11,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0],
    'playerIds': [73798,
     106883,
     437583,
     379868,
     534899,
     39722,
     514810,
     344644,
     300713,
     498798,
     577403,
     345031,
     369109,
     353423,
     415181,
     144890,
     422957,
     317541,
     104010,
     468852,
     623489,
     623490],
    'formationPositions': [{'vertical': 0.0, 'horizontal': 5.0},
     {'vertical': 2.5, 'horizontal': 1.0},
     {'vertical': 2.5, 'horizontal': 9.0},
     {'vertical': 6.0, 'horizontal': 3.5},
     {'vertical': 2.5, 'horizontal': 3.5},
     {'vertical': 2.5, 'horizontal': 6.5},
     {'vertical': 6.0, 'horizontal': 1.0},
     {'vertical': 6.0, 'horizontal': 6.5},
     {'vertical': 9.0, 'horizontal': 6.5},
     {'vertical': 9.0, 'horizontal': 3.5},
     {'vertical': 6.0, 'horizontal': 9.0}]},
   {'formationId': 2,
    'formationName': '442',
    'captainPlayerId': 106883,
    'period': 16,
    'startMinuteExpanded': 73,
    'endMinuteExpanded': 77,
    'jerseyNumbers': [1,
     2,
     18,
     5,
     17,
     24,
     30,
     8,
     10,
     16,
     45,
     13,
     6,
     14,
     15,
     19,
     20,
     21,
     22,
     4,
     50,
     51],
    'formationSlots': [1,
     2,
     3,
     4,
     5,
     6,
     7,
     8,
     9,
     10,
     11,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0],
    'playerIds': [73798,
     106883,
     437583,
     379868,
     534899,
     468852,
     514810,
     344644,
     300713,
     498798,
     577403,
     345031,
     369109,
     353423,
     415181,
     144890,
     422957,
     317541,
     104010,
     39722,
     623489,
     623490],
    'formationPositions': [{'vertical': 0.0, 'horizontal': 5.0},
     {'vertical': 2.5, 'horizontal': 1.0},
     {'vertical': 2.5, 'horizontal': 9.0},
     {'vertical': 6.0, 'horizontal': 3.5},
     {'vertical': 2.5, 'horizontal': 3.5},
     {'vertical': 2.5, 'horizontal': 6.5},
     {'vertical': 6.0, 'horizontal': 1.0},
     {'vertical': 6.0, 'horizontal': 6.5},
     {'vertical': 9.0, 'horizontal': 6.5},
     {'vertical': 9.0, 'horizontal': 3.5},
     {'vertical': 6.0, 'horizontal': 9.0}],
    'subOnPlayerId': 468852,
    'subOffPlayerId': 39722},
   {'formationId': 2,
    'formationName': '442',
    'captainPlayerId': 106883,
    'period': 2,
    'startMinuteExpanded': 77,
    'endMinuteExpanded': 87,
    'jerseyNumbers': [1,
     2,
     18,
     8,
     17,
     24,
     45,
     19,
     10,
     15,
     21,
     13,
     6,
     14,
     20,
     22,
     50,
     51],
    'formationSlots': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 0, 0, 0, 0, 0, 0],
    'playerIds': [73798,
     106883,
     437583,
     344644,
     534899,
     468852,
     577403,
     144890,
     300713,
     415181,
     317541,
     345031,
     369109,
     353423,
     422957,
     104010,
     623489,
     623490],
    'formationPositions': [{'vertical': 0.0, 'horizontal': 5.0},
     {'vertical': 2.5, 'horizontal': 1.0},
     {'vertical': 2.5, 'horizontal': 9.0},
     {'vertical': 6.0, 'horizontal': 3.5},
     {'vertical': 2.5, 'horizontal': 3.5},
     {'vertical': 2.5, 'horizontal': 6.5},
     {'vertical': 6.0, 'horizontal': 1.0},
     {'vertical': 6.0, 'horizontal': 6.5},
     {'vertical': 9.0, 'horizontal': 6.5},
     {'vertical': 9.0, 'horizontal': 3.5},
     {'vertical': 6.0, 'horizontal': 9.0}]},
   {'formationId': 2,
    'formationName': '442',
    'captainPlayerId': 344644,
    'period': 2,
    'startMinuteExpanded': 87,
    'endMinuteExpanded': 92,
    'jerseyNumbers': [1,
     17,
     18,
     8,
     24,
     51,
     45,
     19,
     10,
     15,
     21,
     13,
     6,
     14,
     20,
     22,
     50],
    'formationSlots': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 0, 0, 0, 0, 0],
    'playerIds': [73798,
     534899,
     437583,
     344644,
     468852,
     623490,
     577403,
     144890,
     300713,
     415181,
     317541,
     345031,
     369109,
     353423,
     422957,
     104010,
     623489],
    'formationPositions': [{'vertical': 0.0, 'horizontal': 5.0},
     {'vertical': 2.5, 'horizontal': 1.0},
     {'vertical': 2.5, 'horizontal': 9.0},
     {'vertical': 6.0, 'horizontal': 3.5},
     {'vertical': 2.5, 'horizontal': 3.5},
     {'vertical': 2.5, 'horizontal': 6.5},
     {'vertical': 6.0, 'horizontal': 1.0},
     {'vertical': 6.0, 'horizontal': 6.5},
     {'vertical': 9.0, 'horizontal': 6.5},
     {'vertical': 9.0, 'horizontal': 3.5},
     {'vertical': 6.0, 'horizontal': 9.0}]}],
  'stats': {'minutesWithStats': [0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    13,
    14,
    15,
    16,
    17,
    18,
    20,
    21,
    22,
    23,
    24,
    25,
    26,
    27,
    28,
    29,
    30,
    33,
    34,
    35,
    36,
    37,
    38,
    39,
    40,
    41,
    42,
    43,
    44,
    45,
    46,
    47,
    48,
    49,
    50,
    51,
    52,
    53,
    54,
    55,
    56,
    57,
    58,
    59,
    60,
    61,
    62,
    63,
    64,
    65,
    66,
    67,
    68,
    69,
    70,
    71,
    73,
    74,
    75,
    76,
    77,
    78,
    80,
    81,
    82,
    83,
    84,
    87,
    88,
    89,
    90,
    91,
    93,
    94,
    95],
   'ratings': {'0': 6.00181818181818,
    '1': 6.01272727272727,
    '2': 6.00272727272727,
    '3': 6.00636363636364,
    '4': 6.02090909090909,
    '5': 6.02,
    '6': 6.02636363636364,
    '7': 6.04090909090909,
    '8': 6.04454545454546,
    '9': 6.04818181818182,
    '10': 6.05181818181818,
    '11': 6.30272727272727,
    '13': 6.32,
    '14': 6.32181818181818,
    '15': 6.32818181818182,
    '16': 6.33363636363636,
    '17': 6.34636363636364,
    '18': 6.34454545454545,
    '19': 6.33545454545455,
    '20': 6.35090909090909,
    '21': 6.35181818181818,
    '22': 6.36272727272727,
    '23': 6.37909090909091,
    '24': 6.40454545454546,
    '25': 6.40545454545455,
    '26': 6.39909090909091,
    '27': 6.40545454545455,
    '28': 6.40818181818182,
    '29': 6.41,
    '30': 6.41454545454545,
    '33': 6.41363636363636,
    '34': 6.41727272727273,
    '35': 6.41909090909091,
    '36': 6.42636363636364,
    '37': 6.45454545454545,
    '38': 6.45363636363636,
    '39': 6.45727272727273,
    '40': 6.69909090909091,
    '41': 6.70090909090909,
    '42': 6.70363636363636,
    '43': 6.71090909090909,
    '44': 6.72636363636364,
    '45': 6.58,
    '46': 6.59545454545455,
    '47': 6.6,
    '48': 6.60363636363636,
    '49': 6.60181818181818,
    '50': 6.60090909090909,
    '51': 6.60181818181818,
    '52': 6.60727272727273,
    '53': 6.61636363636364,
    '54': 6.84,
    '55': 6.84727272727273,
    '56': 6.85,
    '57': 6.84909090909091,
    '58': 6.85363636363636,
    '59': 6.84727272727273,
    '60': 6.86636363636364,
    '61': 6.87272727272727,
    '62': 6.87636363636364,
    '63': 6.87727272727273,
    '64': 6.89090909090909,
    '65': 6.89545454545454,
    '66': 6.89727272727273,
    '67': 6.89727272727273,
    '68': 6.9,
    '69': 6.90909090909091,
    '70': 6.91636363636364,
    '71': 6.91727272727273,
    '73': 6.85,
    '74': 6.85,
    '75': 6.84916666666667,
    '76': 6.8575,
    '77': 6.686,
    '78': 6.68733333333333,
    '80': 6.68733333333333,
    '81': 6.68866666666667,
    '82': 6.692,
    '83': 6.69733333333333,
    '84': 6.69866666666667,
    '87': 6.655,
    '88': 6.655625,
    '89': 6.668125,
    '90': 6.678125,
    '91': 6.839375,
    '94': 6.75,
    '95': 6.75},
   'shotsTotal': {'11': 1.0,
    '24': 1.0,
    '34': 1.0,
    '40': 1.0,
    '43': 1.0,
    '52': 1.0,
    '53': 1.0,
    '54': 1.0,
    '59': 1.0,
    '60': 1.0,
    '65': 1.0,
    '90': 1.0,
    '91': 1.0},
   'shotsOnTarget': {'11': 1.0,
    '24': 1.0,
    '40': 1.0,
    '54': 1.0,
    '60': 1.0,
    '65': 1.0,
    '90': 1.0,
    '91': 1.0},
   'shotsOffTarget': {'34': 1.0, '43': 1.0, '52': 1.0, '53': 1.0, '59': 1.0},
   'clearances': {'0': 1.0, '21': 1.0, '22': 3.0, '24': 1.0, '58': 1.0},
   'interceptions': {'4': 1.0,
    '7': 1.0,
    '15': 1.0,
    '36': 1.0,
    '37': 1.0,
    '69': 1.0,
    '73': 1.0},
   'possession': {'0': 7.0,
    '1': 12.0,
    '2': 5.0,
    '3': 2.0,
    '4': 1.0,
    '5': 18.0,
    '6': 14.0,
    '7': 9.0,
    '8': 14.0,
    '9': 12.0,
    '10': 10.0,
    '11': 16.0,
    '13': 12.0,
    '14': 14.0,
    '15': 2.0,
    '16': 20.0,
    '17': 17.0,
    '18': 6.0,
    '20': 7.0,
    '21': 10.0,
    '22': 3.0,
    '23': 9.0,
    '24': 10.0,
    '25': 9.0,
    '26': 6.0,
    '27': 9.0,
    '28': 18.0,
    '29': 18.0,
    '30': 2.0,
    '33': 1.0,
    '34': 3.0,
    '35': 15.0,
    '36': 15.0,
    '37': 2.0,
    '38': 10.0,
    '39': 17.0,
    '40': 1.0,
    '41': 6.0,
    '42': 17.0,
    '43': 19.0,
    '44': 3.0,
    '45': 4.0,
    '46': 17.0,
    '47': 5.0,
    '48': 8.0,
    '49': 9.0,
    '50': 5.0,
    '51': 13.0,
    '52': 8.0,
    '53': 11.0,
    '54': 5.0,
    '56': 14.0,
    '58': 7.0,
    '59': 7.0,
    '60': 5.0,
    '61': 21.0,
    '62': 10.0,
    '63': 9.0,
    '64': 18.0,
    '65': 9.0,
    '66': 8.0,
    '67': 2.0,
    '68': 10.0,
    '69': 5.0,
    '70': 9.0,
    '71': 6.0,
    '73': 4.0,
    '74': 10.0,
    '75': 9.0,
    '76': 8.0,
    '78': 15.0,
    '80': 1.0,
    '81': 9.0,
    '82': 14.0,
    '83': 8.0,
    '84': 14.0,
    '88': 10.0,
    '89': 5.0,
    '90': 1.0,
    '91': 16.0,
    '94': 2.0,
    '95': 8.0},
   'touches': {'0': 10.0,
    '1': 14.0,
    '2': 5.0,
    '3': 2.0,
    '4': 2.0,
    '5': 18.0,
    '6': 16.0,
    '7': 10.0,
    '8': 16.0,
    '9': 14.0,
    '10': 11.0,
    '11': 17.0,
    '13': 13.0,
    '14': 14.0,
    '15': 4.0,
    '16': 20.0,
    '17': 21.0,
    '18': 6.0,
    '20': 10.0,
    '21': 11.0,
    '22': 9.0,
    '23': 10.0,
    '24': 13.0,
    '25': 9.0,
    '26': 8.0,
    '27': 11.0,
    '28': 20.0,
    '29': 18.0,
    '30': 4.0,
    '33': 1.0,
    '34': 4.0,
    '35': 15.0,
    '36': 17.0,
    '37': 5.0,
    '38': 12.0,
    '39': 19.0,
    '40': 2.0,
    '41': 6.0,
    '42': 18.0,
    '43': 20.0,
    '44': 4.0,
    '45': 4.0,
    '46': 19.0,
    '47': 6.0,
    '48': 8.0,
    '49': 9.0,
    '50': 7.0,
    '51': 15.0,
    '52': 9.0,
    '53': 13.0,
    '54': 6.0,
    '55': 2.0,
    '56': 16.0,
    '57': 2.0,
    '58': 9.0,
    '59': 8.0,
    '60': 7.0,
    '61': 22.0,
    '62': 11.0,
    '63': 9.0,
    '64': 22.0,
    '65': 11.0,
    '66': 8.0,
    '67': 3.0,
    '68': 12.0,
    '69': 10.0,
    '70': 12.0,
    '71': 9.0,
    '73': 5.0,
    '74': 11.0,
    '75': 10.0,
    '76': 12.0,
    '78': 15.0,
    '80': 1.0,
    '81': 9.0,
    '82': 16.0,
    '83': 10.0,
    '84': 15.0,
    '88': 12.0,
    '89': 7.0,
    '90': 3.0,
    '91': 17.0,
    '94': 2.0,
    '95': 9.0},
   'passesTotal': {'0': 7.0,
    '1': 12.0,
    '2': 5.0,
    '5': 18.0,
    '6': 14.0,
    '7': 8.0,
    '8': 14.0,
    '9': 12.0,
    '10': 10.0,
    '11': 15.0,
    '13': 11.0,
    '14': 14.0,
    '15': 1.0,
    '16': 20.0,
    '17': 17.0,
    '18': 5.0,
    '20': 7.0,
    '21': 10.0,
    '22': 3.0,
    '23': 8.0,
    '24': 9.0,
    '25': 9.0,
    '26': 6.0,
    '27': 9.0,
    '28': 18.0,
    '29': 18.0,
    '34': 2.0,
    '35': 14.0,
    '36': 15.0,
    '37': 2.0,
    '38': 10.0,
    '39': 17.0,
    '40': 1.0,
    '41': 6.0,
    '42': 17.0,
    '43': 19.0,
    '44': 3.0,
    '45': 4.0,
    '46': 17.0,
    '47': 5.0,
    '48': 8.0,
    '49': 9.0,
    '50': 5.0,
    '51': 13.0,
    '52': 7.0,
    '53': 11.0,
    '54': 5.0,
    '56': 14.0,
    '58': 7.0,
    '59': 7.0,
    '60': 5.0,
    '61': 21.0,
    '62': 10.0,
    '63': 9.0,
    '64': 18.0,
    '65': 9.0,
    '66': 8.0,
    '67': 2.0,
    '68': 10.0,
    '69': 5.0,
    '70': 8.0,
    '71': 6.0,
    '73': 4.0,
    '74': 10.0,
    '75': 8.0,
    '76': 8.0,
    '78': 14.0,
    '81': 9.0,
    '82': 14.0,
    '83': 8.0,
    '84': 14.0,
    '88': 10.0,
    '89': 5.0,
    '91': 16.0,
    '94': 2.0,
    '95': 8.0,
    '3': 2.0,
    '4': 1.0,
    '30': 1.0,
    '33': 1.0,
    '80': 1.0},
   'passesAccurate': {'0': 7.0,
    '1': 11.0,
    '2': 4.0,
    '5': 17.0,
    '6': 14.0,
    '7': 6.0,
    '8': 14.0,
    '9': 12.0,
    '10': 9.0,
    '11': 15.0,
    '13': 9.0,
    '14': 12.0,
    '15': 1.0,
    '16': 19.0,
    '17': 14.0,
    '18': 4.0,
    '20': 5.0,
    '21': 7.0,
    '22': 2.0,
    '23': 7.0,
    '24': 7.0,
    '25': 8.0,
    '26': 4.0,
    '27': 9.0,
    '28': 17.0,
    '29': 16.0,
    '34': 1.0,
    '35': 14.0,
    '36': 13.0,
    '37': 1.0,
    '38': 10.0,
    '39': 17.0,
    '40': 1.0,
    '41': 5.0,
    '42': 16.0,
    '43': 19.0,
    '44': 2.0,
    '45': 4.0,
    '46': 17.0,
    '47': 5.0,
    '48': 8.0,
    '49': 8.0,
    '50': 5.0,
    '51': 11.0,
    '52': 6.0,
    '53': 11.0,
    '54': 4.0,
    '56': 14.0,
    '58': 6.0,
    '59': 6.0,
    '60': 5.0,
    '61': 18.0,
    '62': 10.0,
    '63': 8.0,
    '64': 18.0,
    '65': 6.0,
    '66': 8.0,
    '67': 1.0,
    '68': 10.0,
    '69': 5.0,
    '70': 8.0,
    '71': 6.0,
    '73': 4.0,
    '74': 8.0,
    '75': 6.0,
    '76': 6.0,
    '78': 13.0,
    '81': 9.0,
    '82': 12.0,
    '83': 7.0,
    '84': 13.0,
    '88': 9.0,
    '89': 5.0,
    '91': 16.0,
    '94': 2.0,
    '95': 8.0},
   'passesKey': {'11': 1.0,
    '24': 1.0,
    '40': 1.0,
    '43': 1.0,
    '53': 1.0,
    '54': 1.0,
    '60': 1.0,
    '91': 1.0},
   'passSuccess': {'0': 100.0,
    '1': 91.67,
    '2': 80.0,
    '5': 94.44,
    '6': 100.0,
    '7': 75.0,
    '8': 100.0,
    '9': 100.0,
    '10': 90.0,
    '11': 100.0,
    '13': 81.82,
    '14': 85.71,
    '15': 100.0,
    '16': 95.0,
    '17': 82.35,
    '18': 80.0,
    '20': 71.43,
    '21': 70.0,
    '22': 66.67,
    '23': 87.5,
    '24': 77.78,
    '25': 88.89,
    '26': 66.67,
    '27': 100.0,
    '28': 94.44,
    '29': 88.89,
    '34': 50.0,
    '35': 100.0,
    '36': 86.67,
    '37': 50.0,
    '38': 100.0,
    '39': 100.0,
    '40': 100.0,
    '41': 83.33,
    '42': 94.12,
    '43': 100.0,
    '44': 66.67,
    '45': 100.0,
    '46': 100.0,
    '47': 100.0,
    '48': 100.0,
    '49': 88.89,
    '50': 100.0,
    '51': 84.62,
    '52': 85.71,
    '53': 100.0,
    '54': 80.0,
    '56': 100.0,
    '58': 85.71,
    '59': 85.71,
    '60': 100.0,
    '61': 85.71,
    '62': 100.0,
    '63': 88.89,
    '64': 100.0,
    '65': 66.67,
    '66': 100.0,
    '67': 50.0,
    '68': 100.0,
    '69': 100.0,
    '70': 100.0,
    '71': 100.0,
    '73': 100.0,
    '74': 80.0,
    '75': 75.0,
    '76': 75.0,
    '78': 92.86,
    '81': 100.0,
    '82': 85.71,
    '83': 87.5,
    '84': 92.86,
    '88': 90.0,
    '89': 100.0,
    '91': 100.0,
    '94': 100.0,
    '95': 100.0,
    '3': 0.0,
    '4': 0.0,
    '30': 0.0,
    '33': 0.0,
    '80': 0.0},
   'aerialsTotal': {'3': 2.0,
    '4': 1.0,
    '7': 1.0,
    '20': 1.0,
    '34': 1.0,
    '52': 1.0,
    '21': 1.0,
    '22': 1.0,
    '24': 1.0,
    '26': 1.0,
    '44': 1.0,
    '59': 1.0},
   'aerialsWon': {'3': 1.0,
    '4': 1.0,
    '7': 1.0,
    '20': 1.0,
    '34': 1.0,
    '52': 1.0},
   'aerialSuccess': {'3': 100.0,
    '21': 0.0,
    '22': 0.0,
    '24': 0.0,
    '26': 0.0,
    '44': 0.0,
    '59': 0.0},
   'offensiveAerials': {'24': 1.0},
   'defensiveAerials': {'3': 2.0,
    '4': 1.0,
    '7': 1.0,
    '20': 1.0,
    '21': 1.0,
    '22': 1.0,
    '26': 1.0,
    '34': 1.0,
    '44': 1.0,
    '52': 1.0,
    '59': 1.0},
   'cornersTotal': {'10': 1.0, '33': 1.0},
   'throwInsTotal': {'28': 1.0,
    '39': 1.0,
    '42': 1.0,
    '51': 1.0,
    '57': 1.0,
    '58': 1.0,
    '64': 1.0,
    '65': 1.0,
    '69': 1.0,
    '74': 1.0},
   'throwInsAccurate': {'28': 1.0,
    '39': 1.0,
    '42': 1.0,
    '51': 1.0,
    '57': 1.0,
    '58': 1.0,
    '64': 1.0,
    '65': 1.0,
    '69': 1.0,
    '74': 1.0},
   'offsidesCaught': {'6': 1.0,
    '46': 1.0,
    '57': 1.0,
    '68': 1.0,
    '71': 1.0,
    '84': 1.0,
    '95': 1.0},
   'foulsCommited': {'2': 1.0,
    '4': 1.0,
    '15': 1.0,
    '18': 1.0,
    '36': 1.0,
    '67': 1.0},
   'tacklesTotal': {'20': 1.0,
    '55': 1.0,
    '0': 1.0,
    '1': 1.0,
    '5': 1.0,
    '26': 1.0,
    '60': 2.0,
    '89': 1.0},
   'tackleSuccessful': {'20': 1.0, '55': 1.0},
   'tackleUnsuccesful': {'0': 1.0,
    '1': 1.0,
    '5': 1.0,
    '26': 1.0,
    '60': 2.0,
    '89': 1.0},
   'tackleSuccess': {'20': 100.0,
    '55': 100.0,
    '0': 0.0,
    '1': 0.0,
    '5': 0.0,
    '26': 0.0,
    '60': 0.0,
    '89': 0.0},
   'dribbledPast': {'0': 1.0,
    '1': 1.0,
    '5': 1.0,
    '26': 1.0,
    '60': 2.0,
    '89': 1.0},
   'dribblesWon': {'1': 1.0,
    '13': 1.0,
    '17': 1.0,
    '23': 1.0,
    '37': 1.0,
    '44': 1.0,
    '46': 1.0,
    '64': 1.0,
    '76': 1.0,
    '89': 1.0},
   'dribblesAttempted': {'1': 1.0,
    '13': 1.0,
    '17': 1.0,
    '23': 1.0,
    '37': 1.0,
    '44': 1.0,
    '46': 1.0,
    '64': 1.0,
    '76': 2.0,
    '89': 1.0,
    '8': 1.0,
    '26': 1.0,
    '36': 1.0,
    '39': 1.0,
    '71': 1.0},
   'dribblesLost': {'8': 1.0,
    '26': 1.0,
    '36': 1.0,
    '39': 1.0,
    '71': 1.0,
    '76': 1.0},
   'dribbleSuccess': {'1': 100.0,
    '13': 100.0,
    '17': 100.0,
    '23': 100.0,
    '37': 100.0,
    '44': 100.0,
    '46': 100.0,
    '64': 100.0,
    '76': 50.0,
    '89': 100.0,
    '8': 0.0,
    '26': 0.0,
    '36': 0.0,
    '39': 0.0,
    '71': 0.0},
   'dispossessed': {'15': 1.0, '20': 1.0, '55': 1.0, '69': 1.0}},
  'incidentEvents': [{'id': 2940903037.0,
    'eventId': 37,
    'minute': 2,
    'second': 57,
    'teamId': 52,
    'playerId': 577403,
    'relatedEventId': 36,
    'relatedPlayerId': 577403,
    'x': 0.0,
    'y': 0.0,
    'expandedMinute': 2,

In [41]:
df = pd.DataFrame(evs)
home_team_id = int(data['home']['teamId'])
home_team_name = (data['home']['name'])
away_team_id = int(data['away']['teamId'])
away_team_name = (data['away']['name'])
teams = {
    home_team_id: home_team_name,
    away_team_id: away_team_name
}
players_names = data['playerIdNameDictionary']
df['player_id'] = df['player_id'].apply(lambda x: int(x))
df['player_id'] = df['player_id'].apply(lambda x: str(x))
df['player_name'] = df['player_id'].map(players_names)
df['team_name'] = df['team_id'].map(teams)

,id,eventId,minute,second,teamId,x,y,expandedMinute,period,type,...,endY,relatedEventId,relatedPlayerId,goalMouthZ,goalMouthY,isShot,cardType,isGoal,blockedX,blockedY
0,2.940900e+09,2,0,0.0,52,0.0,0.0,0,"{'value': 1, 'displayName': 'FirstHalf'}","{'value': 32, 'displayName': 'Start'}",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2.940900e+09,2,0,0.0,53,0.0,0.0,0,"{'value': 1, 'displayName': 'FirstHalf'}","{'value': 32, 'displayName': 'Start'}",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2.940900e+09,3,0,0.0,53,50.0,50.0,0,"{'value': 1, 'displayName': 'FirstHalf'}","{'value': 1, 'displayName': 'Pass'}",...,47.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2.940900e+09,4,0,4.0,53,27.0,46.7,0,"{'value': 1, 'displayName': 'FirstHalf'}","{'value': 1, 'displayName': 'Pass'}",...,26.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2.940900e+09,3,0,6.0,52,23.2,76.9,0,"{'value': 1, 'displayName': 'FirstHalf'}","{'value': 12, 'displayName': 'Clearance'}",...,81.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1473,2.940989e+09,538,92,0.0,53,0.0,0.0,96,"{'value': 2, 'displayName': 'SecondHalf'}","{'value': 30, 'displayName': 'End'}",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1474,2.940989e+09,539,0,0.0,53,0.0,0.0,6,"{'value': 14, 'displayName': 'PostGame'}","{'value': 30, 'displayName': 'End'}",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1475,2.940990e+09,1040,0,0.0,52,0.0,0.0,6,"{'value': 14, 'displayName': 'PostGame'}","{'value': 30, 'displayName': 'End'}",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1476,2.940871e+09,1,0,0.0,53,0.0,0.0,0,"{'value': 16, 'displayName': 'PreMatch'}","{'value': 34, 'displayName': 'FormationSet'}",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1477,2.940871e+09,1,0,0.0,52,0.0,0.0,0,"{'value': 16, 'displayName': 'PreMatch'}","{'value': 34, 'displayName': 'FormationSet'}",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
response = requests.get("https://www.whoscored.com", headers=headers)
print(response.status_code)
print(response.text[:2000])   # first 2000 chars to inspect

403
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>
<title>Attention Required! | Cloudflare</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" />
<!--[if lt IE 9]><link rel="stylesheet" id='cf_styles-ie-css' href="/cdn-cgi/styles/cf.errors.ie.css" /><![endif]-->
<style>body{margin:0;padding:0}</style>


<!--[if gte IE 10]><!-->
<script>
  if (!navigator.cookieEnabled) {
    window.addEventListener('DOMContentLoaded', function () {
      var cookieEl = document.getElementById('cookie-alert');
      cookieEl.style.display = 'block';
    })
  }
</script>
<!--<![endif]-->

</head>
<body>
  <div id="cf-wrapper">
    <div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>
    <div id="cf-error-details" class="cf-error-details-wrapper">
      <div class="cf-wrapper cf-header cf-error-overview">
        <h1 data-translate="block_headline">Sorry, you have been blocked</h1>
        <h2 class="cf-subheadline"><span data-translate="unable_to_access">You are unable to access</span> whoscored.com</h2>
      </div><!-- /.header -->

      <div class="cf-section cf-highlight">
        <div class="cf-wrapper">
          <div class="cf-screenshot-container cf-screenshot-full">

              <span class="cf-no-screenshot error"></span>

          </div>
        </div>
      </div><!-- /.captcha-container -->

      <di

In [31]:
link = "https://www.whoscored.com" + "/Regions/206/Tournaments/4/Seasons/10317/spain-laliga"
res1 = requests.get(link, headers=headers, impersonate="chrome120")
soup = BeautifulSoup(res1.text, 'html.parser')
miaww = soup.find(attrs = {"id" :"link-fixtures"})

In [32]:
miaww['href']

'/regions/206/tournaments/4/seasons/10317/stages/23401/fixtures/spain-laliga-2024-2025'

In [ ]:
new_l

In [ ]:
link = "https://www.whoscored.com/tournaments/24622/data/?d=202511"
response = requests.get(link, headers = headers, impersonate="chrome120", timeout=30)

In [ ]:
data = response.json()
match_ids = []

In [ ]:
for tourney in data.get('tournaments', []):
    for match in tourney.get('matches', []):
        match_ids.append(match['id'])

In [ ]:
match_ids

In [ ]:
urlll = "https://www.whoscored.com/matches/1914256/live/spain-laliga-2025-2026-real-madrid-athletic-club"
inds = urlll.split("/")
inds

In [ ]:
inds[4]

In [ ]:
name = inds[len(inds) - 1]

In [ ]:
name

In [ ]:
name

In [ ]:
import re
pattern = re.compile(r'matches/(\d+)/.*?/[^-]+-(.+?)-(\d{4}-\d{4})')
match = pattern.search(urlll)

In [ ]:
id = match.group(1)

In [ ]:
id

In [ ]:
league = match.group(2)

In [ ]:
league

In [ ]:
season = match.group(3)
season

In [ ]:
from socceraction.data.opta.parsers import WhoScoredParser
from socceraction.spadl.opta import convert_to_actions
from socceraction.data.opta.loader import _eventtypesdf

In [ ]:
import tempfile
temp_file = tempfile.NamedTemporaryFile(mode='w', suffix='.json', delete=False)
temp_path = temp_file.name
json.dump(data, temp_file)
temp_file.close() #
parser = WhoScoredParser(
    path = temp_path,
    competition_id = league,
    season_id = season,
    game_id = id,
)

In [ ]:
parser.extract_events()

In [ ]:
import pandas as pd
df_events = pd.DataFrame.from_dict(parser.extract_events(), orient="index")
df_events = df_events.merge(_eventtypesdf, on="type_id", how="left").reset_index(drop=True)

In [ ]:
df_spadl = convert_to_actions(df_events, home_team_id=19)

In [ ]:
df_spadl

In [ ]:
from socceraction.spadl import config as spadlconfig

In [ ]:
df_spadl = pd.merge(df_spadl, spadlconfig.actiontypes_df(), on='type_id', how='inner')
df_spadl = pd.merge(df_spadl, spadlconfig.results_df(), on='result_id', how='inner')
df_spadl = pd.merge(df_spadl, spadlconfig.bodyparts_df(), on='bodypart_id', how='inner')

In [ ]:
df_spadl

In [ ]:
data

In [ ]:
int(data['home']['teamId'])

In [ ]:
data['playerIdNameDictionary']

In [ ]:
df_spadl['player_id'] = df_spadl['player_id'].apply(lambda x: int(x))

In [ ]:
df_spadl

In [ ]:
pnames = data['playerIdNameDictionary']
df_spadl['player_id'] = df_spadl['player_id'].apply(lambda x: str(x))
df_spadl['player_name'] = df_spadl['player_id'].map(pnames)

In [ ]:
df_spadl

In [ ]:
data['home']

In [ ]:
home_team_id = int(data['home']['teamId'])
home_team_name = (data['home']['name'])
away_team_id = int(data['away']['teamId'])
away_team_name = (data['away']['name'])
teams = {
    home_team_id : home_team_name,
    away_team_id : away_team_name
}

In [ ]:
df_spadl['team_name'] = df_spadl['team_id'].map(teams)

In [ ]:
df_spadl

In [ ]:
data

In [34]:
res = requests.get("https://www.whoscored.com/regions/206/tournaments/4/spain-laliga", headers = headers, impersonate = "chrome120")

In [35]:
soup = BeautifulSoup(res.text, 'html.parser')

In [36]:
miaw = soup.find(attrs = {"id" :"seasons","name":"seasons"})

In [38]:
miaw.contents

[<option selected="selected" value="/Regions/206/Tournaments/4/Seasons/10803/spain-laliga">2025/2026</option>,
 '\n',
 <option value="/Regions/206/Tournaments/4/Seasons/10317/spain-laliga">2024/2025</option>,
 '\n',
 <option value="/Regions/206/Tournaments/4/Seasons/9682/spain-laliga">2023/2024</option>,
 '\n',
 <option value="/Regions/206/Tournaments/4/Seasons/9149/spain-laliga">2022/2023</option>,
 '\n',
 <option value="/Regions/206/Tournaments/4/Seasons/8681/spain-laliga">2021/2022</option>,
 '\n',
 <option value="/Regions/206/Tournaments/4/Seasons/8321/spain-laliga">2020/2021</option>,
 '\n',
 <option value="/Regions/206/Tournaments/4/Seasons/7889/spain-laliga">2019/2020</option>,
 '\n',
 <option value="/Regions/206/Tournaments/4/Seasons/7466/spain-laliga">2018/2019</option>,
 '\n',
 <option value="/Regions/206/Tournaments/4/Seasons/6960/spain-laliga">2017/2018</option>,
 '\n',
 <option value="/Regions/206/Tournaments/4/Seasons/6436/spain-laliga">2016/2017</option>,
 '\n',
 <option value="/Regions/206/Tournaments/4/Seasons/5933/spain-laliga">2015/2016</option>,
 '\n',
 <option value="/Regions/206/Tournaments/4/Seasons/5435/spain-laliga">2014/2015</option>,
 '\n',
 <option value="/Regions/206/Tournaments/4/Seasons/3922/spain-laliga">2013/2014</option>,
 '\n',
 <option value="/Regions/206/Tournaments/4/Seasons/3470/spain-laliga">2012/2013</option>,
 '\n',
 <option value="/Regions/206/Tournaments/4/Seasons/3004/spain-laliga">2011/2012</option>,
 '\n',
 <option value="/Regions/206/Tournaments/4/Seasons/2596/spain-laliga">2010/2011</option>,
 '\n',
 <option value="/Regions/206/Tournaments/4/Seasons/1929/spain-laliga">2009/2010</option>,
 '\n',
 <option value="/Regions/206/Tournaments/4/Seasons/1562/spain-laliga">2008/2009</option>,
 '\n',
 <option value="/Regions/206/Tournaments/4/Seasons/1297/spain-laliga">2007/2008</option>,
 '\n',
 <option value="/Regions/206/Tournaments/4/Seasons/693/spain-laliga">2006/2007</option>,
 '\n',
 <option value="/Regions/206/Tournaments/4/Seasons/861/spain-laliga">2005/2006</option>,
 '\n',
 <option value="/Regions/206/Tournaments/4/Seasons/610/spain-laliga">2004/2005</option>,
 '\n',
 <option value="/Regions/206/Tournaments/4/Seasons/442/spain-laliga">2003/2004</option>,
 '\n',
 <option value="/Regions/206/Tournaments/4/Seasons/308/spain-laliga">2002/2003</option>,
 '\n',
 <option value="/Regions/206/Tournaments/4/Seasons/201/spain-laliga">2001/2002</option>,
 '\n',
 <option value="/Regions/206/Tournaments/4/Seasons/94/spain-laliga">2000/2001</option>,
 '\n',
 <option value="/Regions/206/Tournaments/4/Seasons/4/spain-laliga">1999/2000</option>,
 '\n']

In [ ]:
listt = [x for x in miaw.contents if x != '\n']

In [1]:
import pandas as pd

In [23]:
df_subset = pd.read_parquet(
    '../data/game_states',
    engine='pyarrow',
    filters=[('game_id', '=', 1914251)]
)

In [24]:
df_subset

,type_id_a0,type_id_a1,type_id_a2,type_pass_a0,type_cross_a0,type_throw_in_a0,type_freekick_crossed_a0,type_freekick_short_a0,type_corner_crossed_a0,type_corner_short_a0,...,time_seconds_overall_a1,period_id_a2,time_seconds_a2,time_seconds_overall_a2,time_delta_1,time_delta_2,scores,concedes,goal_from_shot,game_id
0,0,0,0,True,False,False,False,False,False,False,...,0.0,1,0.0,0.0,0.0,0.0,False,False,False,1914251
1,0,0,0,True,False,False,False,False,False,False,...,0.0,1,0.0,0.0,2.0,2.0,False,False,False,1914251
2,0,0,0,True,False,False,False,False,False,False,...,2.0,1,0.0,0.0,5.0,7.0,False,False,False,1914251
3,0,0,0,True,False,False,False,False,False,False,...,7.0,1,2.0,2.0,36.0,41.0,False,False,False,1914251
4,0,0,0,True,False,False,False,False,False,False,...,43.0,1,7.0,7.0,0.0,36.0,False,False,False,1914251
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1582,11,11,11,False,False,False,False,False,False,False,...,5040.0,2,1712.0,4412.0,658.0,1286.0,False,False,False,1914251
1583,1,11,11,False,True,False,False,False,False,False,...,5698.0,2,2340.0,5040.0,-1465.0,-807.0,False,False,False,1914251
1584,1,1,11,False,True,False,False,False,False,False,...,4233.0,2,2998.0,5698.0,322.0,-1143.0,False,False,False,1914251
1585,1,1,1,False,True,False,False,False,False,False,...,4555.0,2,1533.0,4233.0,689.0,1011.0,False,False,False,1914251
1586,1,1,1,False,True,False,False,False,False,False,...,5244.0,2,1855.0,4555.0,335.0,1024.0,False,False,False,1914251

In [4]:
import socceraction.vaep.features as fs
xfns = [
    fs.actiontype,
    fs.actiontype_onehot,
    fs.bodypart,
    fs.bodypart_onehot,
    fs.result,
    fs.result_onehot,
    fs.goalscore,
    fs.startlocation,
    fs.endlocation,
    fs.movement,
    fs.space_delta,
    fs.startpolar,
    fs.endpolar,
    fs.team,
    fs.time,
    fs.time_delta
]

In [5]:
import socceraction.vaep.labels as lab
yfns = [
    lab.scores,
    lab.concedes,
    lab.goal_from_shot
]

In [6]:
type(df_subset)

pandas.core.frame.DataFrame

In [7]:
print(df_subset.select_dtypes(include=['category']).columns)

Index(['game_id'], dtype='object')

In [8]:
cat_cols = df_subset.select_dtypes(include=['category']).columns
df_subset[cat_cols] = df_subset[cat_cols].astype('object')

In [9]:
gs = fs.gamestates(df_subset, nb_prev_actions=3)

In [10]:
type(gs)

list

In [11]:
unique_teams = df_subset['team_id'].unique()
home_team_id = unique_teams[0]

In [12]:
gamestates = fs.play_left_to_right(gs, home_team_id)

In [13]:
X = pd.concat([fn(gamestates) for fn in xfns], axis=1)
X = pd.concat([X,df_subset['game_id']], axis = 1)

In [14]:
X

,type_id_a0,type_id_a1,type_id_a2,type_pass_a0,type_cross_a0,type_throw_in_a0,type_freekick_crossed_a0,type_freekick_short_a0,type_corner_crossed_a0,type_corner_short_a0,...,time_seconds_overall_a0,period_id_a1,time_seconds_a1,time_seconds_overall_a1,period_id_a2,time_seconds_a2,time_seconds_overall_a2,time_delta_1,time_delta_2,game_id
0,0,0,0,True,False,False,False,False,False,False,...,0.0,1,0.0,0.0,1,0.0,0.0,0.0,0.0,1914251
1,0,0,0,True,False,False,False,False,False,False,...,2.0,1,0.0,0.0,1,0.0,0.0,2.0,2.0,1914251
2,0,0,0,True,False,False,False,False,False,False,...,7.0,1,2.0,2.0,1,0.0,0.0,5.0,7.0,1914251
3,0,0,0,True,False,False,False,False,False,False,...,43.0,1,7.0,7.0,1,2.0,2.0,36.0,41.0,1914251
4,0,0,0,True,False,False,False,False,False,False,...,43.0,1,43.0,43.0,1,7.0,7.0,0.0,36.0,1914251
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6343,11,11,11,False,False,False,False,False,False,False,...,5698.0,2,2340.0,5040.0,2,1712.0,4412.0,658.0,1286.0,1914251
6344,1,11,11,False,True,False,False,False,False,False,...,4233.0,2,2998.0,5698.0,2,2340.0,5040.0,-1465.0,-807.0,1914251
6345,1,1,11,False,True,False,False,False,False,False,...,4555.0,2,1533.0,4233.0,2,2998.0,5698.0,322.0,-1143.0,1914251
6346,1,1,1,False,True,False,False,False,False,False,...,5244.0,2,1855.0,4555.0,2,1533.0,4233.0,689.0,1011.0,1914251
6347,1,1,1,False,True,False,False,False,False,False,...,5579.0,2,2544.0,5244.0,2,1855.0,4555.0,335.0,1024.0,1914251

In [15]:
Y = pd.concat([fn(df_subset) for fn in yfns], axis=1)
Y = pd.concat([Y, df_subset['game_id']], axis=1)

In [16]:
X.shape

(6348, 164)

In [17]:
Y.shape

(6348, 4)

In [18]:
result = pd.concat([X, Y],axis = 1)

In [19]:
result

,type_id_a0,type_id_a1,type_id_a2,type_pass_a0,type_cross_a0,type_throw_in_a0,type_freekick_crossed_a0,type_freekick_short_a0,type_corner_crossed_a0,type_corner_short_a0,...,period_id_a2,time_seconds_a2,time_seconds_overall_a2,time_delta_1,time_delta_2,game_id,scores,concedes,goal_from_shot,game_id
0,0,0,0,True,False,False,False,False,False,False,...,1,0.0,0.0,0.0,0.0,1914251,False,False,False,1914251
1,0,0,0,True,False,False,False,False,False,False,...,1,0.0,0.0,2.0,2.0,1914251,False,False,False,1914251
2,0,0,0,True,False,False,False,False,False,False,...,1,0.0,0.0,5.0,7.0,1914251,False,False,False,1914251
3,0,0,0,True,False,False,False,False,False,False,...,1,2.0,2.0,36.0,41.0,1914251,False,False,False,1914251
4,0,0,0,True,False,False,False,False,False,False,...,1,7.0,7.0,0.0,36.0,1914251,False,False,False,1914251
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6343,11,11,11,False,False,False,False,False,False,False,...,2,1712.0,4412.0,658.0,1286.0,1914251,False,False,False,1914251
6344,1,11,11,False,True,False,False,False,False,False,...,2,2340.0,5040.0,-1465.0,-807.0,1914251,False,False,False,1914251
6345,1,1,11,False,True,False,False,False,False,False,...,2,2998.0,5698.0,322.0,-1143.0,1914251,False,False,False,1914251
6346,1,1,1,False,True,False,False,False,False,False,...,2,1533.0,4233.0,689.0,1011.0,1914251,False,False,False,1914251
6347,1,1,1,False,True,False,False,False,False,False,...,2,1855.0,4555.0,335.0,1024.0,1914251,False,False,False,1914251

In [53]:
Y['concedes'] == False

0       True
1       True
2       True
3       True
4       True
        ...
1582    True
1583    True
1584    True
1585    True
1586    True
Name: concedes, Length: 1587, dtype: bool

In [1]:
import pandas as pd
df_subset = pd.read_parquet(
    '../data/game_states',
    engine='pyarrow',
    filters=[('game_id', '=', 1914251)]
)

In [6]:
df_subset

NameError: name 'df_subset' is not defined

In [2]:
import pandas as pd
df_subset = pd.read_parquet(
    '../data/spadl',
    engine='pyarrow',
    filters=[('game_id', '=', 1914251)]
)

In [9]:
df_subset.columns

Index(['original_event_id', 'period_id', 'time_seconds', 'team_id',
       'player_id', 'start_x', 'end_x', 'start_y', 'end_y', 'type_id',
       'result_id', 'bodypart_id', 'action_id', 'type_name', 'result_name',
       'bodypart_name', 'player_name', 'team_name', 'game_id'],
      dtype='object')